### PR TITLE
Update Capacitor.getPlatform() === 'web' to Capacitor.isNativePlatform()

### PR DESCRIPTION
**Pull request by Quante31**
Issue #834 Update Capacitor.getPlatform() === 'web' to Capacitor.isNativePlatform()

### CODE REVIEW

**Review by xuelink — CHANGES_REQUESTED** [review]
Perfect! Can you please update them with negative of`!Capacitor.isNativePlatform()`

**Comment by Quante31** [comment]
Done.

**Review by xuelink — APPROVED** [review]
Well Done! Thank you for your contribution!! :)

**Comment by xuelink** [comment]
Also invited you to our organization here.
Mail has been sent. @Quante31

**Pull request merged**
